dataset:
wsi_dir: "data/WSI"
patch_dir: "data/patches"
mask_dir: "data/mask"
split_dir: "data/split"


training:
batch_size: 32
num_epochs: 50
learning_rate: 0.0001
optimizer: "adamw"
scheduler: "cosine"
device: "cuda"


model:
backbone: "resnet50"
num_classes: 2
dropout: 0.5